# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_gpu_calibration_freeze.ipynb.

# %% auto #0
__all__ = ['CANONICAL_CAMPAIGN', 'CampaignConfig']

# %% ../notebooks/07_gpu_calibration_freeze.ipynb #imports-config-07
from dataclasses import dataclass


@dataclass(frozen=True)
class CampaignConfig:
    """Frozen dimensions and resource limits for canonical training."""

    vocabulary_size: int
    d_model: int
    num_heads: int
    d_ff: int
    num_layers: int
    max_sequence_length: int
    dropout: float
    token_budget_per_side: int
    training_examples: int
    max_steps: int
    warmup_steps: int
    label_smoothing: float
    sample_every_steps: int
    sample_count: int
    sample_max_new_tokens: int
    runtime_overhead_multiplier: float


CANONICAL_CAMPAIGN = CampaignConfig(
    vocabulary_size=37_000,
    d_model=512,
    num_heads=8,
    d_ff=2_048,
    num_layers=6,
    max_sequence_length=256,
    dropout=0.1,
    token_budget_per_side=4_096,
    training_examples=4_000_000,
    max_steps=400_000,
    warmup_steps=4_000,
    label_smoothing=0.1,
    sample_every_steps=10_000,
    sample_count=3,
    sample_max_new_tokens=64,
    runtime_overhead_multiplier=1.15,
)

