# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/06_checkpoint_resume.ipynb.

# %% auto #0
__all__ = ['save_atomically', 'save_checkpoint', 'load_checkpoint']

# %% ../notebooks/06_checkpoint_resume.ipynb #6e312d58e9e70011
import os
from pathlib import Path
from typing import Any

import torch

from .model import Transformer


def save_atomically(obj: Any, path: Path) -> None:
    """Serialize with torch.save so a crash never leaves a partial file at `path`."""
    part_path = path.with_suffix(path.suffix + ".part")
    with part_path.open("wb") as handle:
        torch.save(obj, handle)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(part_path, path)


def save_checkpoint(
    path: Path,
    model: Transformer,
    optimizer: torch.optim.Optimizer,
    step: int,
) -> None:
    """Save the minimal CPU training state needed to resume."""
    if step < 0:
        raise ValueError("step must be non-negative")

    checkpoint = {
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "step": step,
        "torch_rng_state": torch.get_rng_state(),
    }

    save_atomically(checkpoint, path)

# %% ../notebooks/06_checkpoint_resume.ipynb #228049b8d6a98507
def load_checkpoint(
    path: Path,
    model: Transformer,
    optimizer: torch.optim.Optimizer,
) -> int:
    """Restore minimal CPU training state and return the saved step."""
    checkpoint = torch.load(
        path,
        map_location="cpu",
        weights_only=True,
    )

    model.load_state_dict(checkpoint["model"])
    optimizer.load_state_dict(checkpoint["optimizer"])
    torch.set_rng_state(checkpoint["torch_rng_state"])

    return checkpoint["step"]
