# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/01_data_contracts_provenance.ipynb.

# %% ../notebooks/01_data_contracts_provenance.ipynb #contracts-code-01
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import tarfile
import time
from collections.abc import Iterator, Sequence
from itertools import zip_longest
from pathlib import Path
from typing import Final, Literal, cast
from urllib.error import URLError
from urllib.request import Request, urlopen

from pydantic import BaseModel, ConfigDict

Split = Literal["train", "development"]


class ParallelExample(BaseModel):
    """One aligned English source and German target sentence."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    source_text: str
    target_text: str


class CorpusSource(BaseModel):
    """Pinned WMT archive and paired members consumed by the pipeline."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    name: str
    split: Split
    url: str
    archive_filename: str
    source_member: str
    target_member: str


class AcquisitionRecord(BaseModel):
    """Content identity of one downloaded source archive."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    name: str
    url: str
    relative_path: str
    sha256: str
    byte_count: int


class SourceProcessingRecord(BaseModel):
    """Deterministic processing counts for one parallel source."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    name: str
    split: Split
    input_pairs: int
    emitted_pairs: int
    skipped_empty_pairs: int


class ShardRecord(BaseModel):
    """Identity and summary of one immutable JSON Lines shard."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    split: Split
    source_name: str
    relative_path: str
    sha256: str
    example_count: int
    byte_count: int


class DatasetManifest(BaseModel):
    """Complete identity of the acquired and sharded WMT14 dataset."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    schema_version: int
    dataset_name: str
    source_language: str
    target_language: str
    shard_size: int
    acquisitions: tuple[AcquisitionRecord, ...]
    sources: tuple[SourceProcessingRecord, ...]
    shards: tuple[ShardRecord, ...]
    total_examples: int


WMT14_EN_DE_SOURCES: Final[tuple[CorpusSource, ...]] = (
    CorpusSource(
        name="europarl-v7",
        split="train",
        url="https://statmt.org/wmt13/training-parallel-europarl-v7.tgz",
        archive_filename="training-parallel-europarl-v7.tgz",
        source_member="training/europarl-v7.de-en.en",
        target_member="training/europarl-v7.de-en.de",
    ),
    CorpusSource(
        name="commoncrawl",
        split="train",
        url="https://statmt.org/wmt13/training-parallel-commoncrawl.tgz",
        archive_filename="training-parallel-commoncrawl.tgz",
        source_member="commoncrawl.de-en.en",
        target_member="commoncrawl.de-en.de",
    ),
    CorpusSource(
        name="news-commentary-v9",
        split="train",
        url="https://statmt.org/wmt14/training-parallel-nc-v9.tgz",
        archive_filename="training-parallel-nc-v9.tgz",
        source_member="training/news-commentary-v9.de-en.en",
        target_member="training/news-commentary-v9.de-en.de",
    ),
    CorpusSource(
        name="newstest2013",
        split="development",
        url="https://statmt.org/wmt14/dev.tgz",
        archive_filename="dev.tgz",
        source_member="dev/newstest2013.en",
        target_member="dev/newstest2013.de",
    ),
)

# %% auto #0
__all__ = ['Split', 'WMT14_EN_DE_SOURCES', 'ParallelExample', 'CorpusSource', 'AcquisitionRecord', 'SourceProcessingRecord',
           'ShardRecord', 'DatasetManifest', 'sha256_bytes', 'sha256_file', 'serialize_examples', 'download_archive',
           'extract_parallel_source', 'shard_parallel_source', 'manifest_as_bytes', 'write_manifest', 'load_manifest',
           'prepare_wmt14_en_de', 'load_shard', 'iter_manifest_examples', 'iter_bpe_training_text', 'main']

# %% ../notebooks/01_data_contracts_provenance.ipynb #pipeline-code-01
def sha256_bytes(content: bytes) -> str:
    """Return the lowercase SHA-256 digest of bytes."""

    return hashlib.sha256(content).hexdigest()


def sha256_file(path: Path) -> str:
    """Return the lowercase SHA-256 digest of a file without loading it whole."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def serialize_examples(examples: Sequence[ParallelExample]) -> bytes:
    """Serialize examples as deterministic UTF-8 JSON Lines bytes."""

    return b"".join((example.model_dump_json() + "\n").encode("utf-8") for example in examples)


def _download_once(url: str, destination: Path) -> None:
    part_path = destination.with_suffix(destination.suffix + ".part")
    offset = part_path.stat().st_size if part_path.exists() else 0
    headers = {"User-Agent": "transformer-2017-reproduction/0.1"}
    if offset:
        headers["Range"] = f"bytes={offset}-"

    request = Request(url, headers=headers)
    with urlopen(request, timeout=120) as response:
        status = response.getcode()
        append = offset > 0 and status == 206
        mode = "ab" if append else "wb"
        with part_path.open(mode) as output:
            shutil.copyfileobj(response, output, length=1024 * 1024)
    part_path.replace(destination)


def download_archive(source: CorpusSource, archive_dir: Path) -> AcquisitionRecord:
    """Download one archive with retry/resume and return its content identity."""

    archive_dir.mkdir(parents=True, exist_ok=True)
    destination = archive_dir / source.archive_filename
    if not destination.exists():
        last_error: OSError | URLError | None = None
        for attempt in range(1, 6):
            try:
                _download_once(source.url, destination)
                break
            except (OSError, URLError) as error:
                last_error = error
                if attempt == 5:
                    raise RuntimeError(f"failed to download {source.url}") from last_error
                time.sleep(float(attempt))

    return AcquisitionRecord(
        name=source.name,
        url=source.url,
        relative_path=destination.as_posix(),
        sha256=sha256_file(destination),
        byte_count=destination.stat().st_size,
    )


def _copy_archive_member(archive: tarfile.TarFile, member_name: str, destination: Path) -> None:
    if destination.exists():
        return
    member = archive.getmember(member_name)
    extracted = archive.extractfile(member)
    if extracted is None:
        raise FileNotFoundError(f"archive member is not a file: {member_name}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    part_path = destination.with_suffix(destination.suffix + ".part")
    with extracted, part_path.open("wb") as output:
        shutil.copyfileobj(extracted, output, length=1024 * 1024)
    part_path.replace(destination)


def extract_parallel_source(
    source: CorpusSource,
    archive_path: Path,
    extracted_dir: Path,
) -> tuple[Path, Path]:
    """Extract only the English and German members needed from an archive."""

    source_path = extracted_dir / f"{source.name}.en"
    target_path = extracted_dir / f"{source.name}.de"
    if source_path.exists() and target_path.exists():
        return source_path, target_path

    with tarfile.open(archive_path, mode="r:gz") as archive:
        _copy_archive_member(archive, source.source_member, source_path)
        _copy_archive_member(archive, source.target_member, target_path)
    return source_path, target_path


def _write_immutable_shard(
    root: Path,
    relative_path: str,
    *,
    split: Split,
    source_name: str,
    examples: Sequence[ParallelExample],
) -> ShardRecord:
    content = serialize_examples(examples)
    shard_path = root / relative_path
    shard_path.parent.mkdir(parents=True, exist_ok=True)
    if shard_path.exists():
        if shard_path.read_bytes() != content:
            raise FileExistsError(f"refusing to replace immutable shard: {shard_path}")
    else:
        part_path = shard_path.with_suffix(shard_path.suffix + ".part")
        part_path.write_bytes(content)
        part_path.replace(shard_path)

    return ShardRecord(
        split=split,
        source_name=source_name,
        relative_path=relative_path,
        sha256=sha256_bytes(content),
        example_count=len(examples),
        byte_count=len(content),
    )


def shard_parallel_source(
    root: Path,
    source: CorpusSource,
    source_path: Path,
    target_path: Path,
    shard_size: int,
) -> tuple[tuple[ShardRecord, ...], SourceProcessingRecord]:
    """Stream aligned files into deterministic immutable shards."""

    if shard_size < 1:
        raise ValueError("shard_size must be at least 1")

    records: list[ShardRecord] = []
    batch: list[ParallelExample] = []
    input_pairs = 0
    emitted_pairs = 0
    skipped_empty_pairs = 0
    shard_index = 0
    shard_root = f"processed/shards-{shard_size}/{source.split}"

    with (
        source_path.open("r", encoding="utf-8", newline="\n") as source_handle,
        target_path.open("r", encoding="utf-8", newline="\n") as target_handle,
    ):
        for source_line, target_line in zip_longest(source_handle, target_handle):
            if source_line is None or target_line is None:
                raise ValueError(f"unaligned line counts for {source.name}")
            input_pairs += 1
            source_text = source_line.rstrip("\r\n")
            target_text = target_line.rstrip("\r\n")
            if not source_text or not target_text:
                skipped_empty_pairs += 1
                continue

            batch.append(
                ParallelExample(
                    source_text=source_text,
                    target_text=target_text,
                )
            )
            emitted_pairs += 1
            if len(batch) == shard_size:
                relative_path = f"{shard_root}/{source.name}-{shard_index:05d}.jsonl"
                records.append(
                    _write_immutable_shard(
                        root,
                        relative_path,
                        split=source.split,
                        source_name=source.name,
                        examples=batch,
                    )
                )
                batch = []
                shard_index += 1

    if batch:
        relative_path = f"{shard_root}/{source.name}-{shard_index:05d}.jsonl"
        records.append(
            _write_immutable_shard(
                root,
                relative_path,
                split=source.split,
                source_name=source.name,
                examples=batch,
            )
        )

    processing = SourceProcessingRecord(
        name=source.name,
        split=source.split,
        input_pairs=input_pairs,
        emitted_pairs=emitted_pairs,
        skipped_empty_pairs=skipped_empty_pairs,
    )
    return tuple(records), processing


def manifest_as_bytes(manifest: DatasetManifest) -> bytes:
    """Serialize a manifest deterministically for storage and hashing."""

    return (manifest.model_dump_json(indent=2) + "\n").encode("utf-8")


def write_manifest(root: Path, manifest: DatasetManifest) -> Path:
    """Write the deterministic manifest, refusing an identity-changing replacement."""

    path = root / "manifests" / f"{manifest.dataset_name}.json"
    content = manifest_as_bytes(manifest)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() != content:
        raise FileExistsError(f"refusing to replace manifest with different content: {path}")
    if not path.exists():
        part_path = path.with_suffix(path.suffix + ".part")
        part_path.write_bytes(content)
        part_path.replace(path)
    return path


def load_manifest(path: Path) -> DatasetManifest:
    """Load and validate a dataset manifest from disk."""

    return DatasetManifest.model_validate_json(path.read_bytes())


def prepare_wmt14_en_de(root: Path, shard_size: int = 100_000) -> DatasetManifest:
    """Acquire and shard all approved WMT14 English-German train/development data."""

    archive_dir = root / "raw" / "archives"
    extracted_dir = root / "raw" / "parallel"
    acquisitions: list[AcquisitionRecord] = []
    source_records: list[SourceProcessingRecord] = []
    shard_records: list[ShardRecord] = []

    for source in WMT14_EN_DE_SOURCES:
        acquisition = download_archive(source, archive_dir)
        archive_path = archive_dir / source.archive_filename
        acquisitions.append(
            acquisition.model_copy(
                update={"relative_path": archive_path.relative_to(root).as_posix()}
            )
        )
        source_path, target_path = extract_parallel_source(
            source,
            archive_path,
            extracted_dir,
        )
        records, processing = shard_parallel_source(
            root,
            source,
            source_path,
            target_path,
            shard_size,
        )
        shard_records.extend(records)
        source_records.append(processing)

    manifest = DatasetManifest(
        schema_version=1,
        dataset_name=f"wmt14-en-de-shard-{shard_size}",
        source_language="en",
        target_language="de",
        shard_size=shard_size,
        acquisitions=tuple(acquisitions),
        sources=tuple(source_records),
        shards=tuple(shard_records),
        total_examples=sum(record.emitted_pairs for record in source_records),
    )
    write_manifest(root, manifest)
    return manifest


def load_shard(root: Path, record: ShardRecord) -> tuple[ParallelExample, ...]:
    """Verify and load one shard."""

    path = root / record.relative_path
    content = path.read_bytes()
    if len(content) != record.byte_count:
        raise ValueError(f"byte count mismatch for {record.relative_path}")
    if sha256_bytes(content) != record.sha256:
        raise ValueError(f"SHA-256 mismatch for {record.relative_path}")
    examples = tuple(ParallelExample.model_validate_json(line) for line in content.splitlines())
    if len(examples) != record.example_count:
        raise ValueError(f"example count mismatch for {record.relative_path}")
    return examples


def iter_manifest_examples(
    root: Path,
    manifest: DatasetManifest,
    split: Split,
) -> Iterator[ParallelExample]:
    """Yield verified examples one shard at a time for a selected split."""

    for record in manifest.shards:
        if record.split == split:
            yield from load_shard(root, record)


def iter_bpe_training_text(root: Path, manifest: DatasetManifest) -> Iterator[str]:
    """Yield source then target text for shared BPE training."""

    for example in iter_manifest_examples(root, manifest, "train"):
        yield example.source_text
        yield example.target_text

# %% ../notebooks/01_data_contracts_provenance.ipynb #cli-code-01
def main(argv: Sequence[str] | None = None) -> int:
    """Run the complete WMT14 English-German acquisition and sharding pipeline."""

    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("--root", default="data/wmt14_en_de")
    parser.add_argument("--shard-size", type=int, default=100_000)
    args = parser.parse_args(argv)
    root = Path(cast(str, args.root))
    shard_size = cast(int, args.shard_size)
    manifest = prepare_wmt14_en_de(root, shard_size)
    manifest_path = root / "manifests" / f"{manifest.dataset_name}.json"
    report = {
        "manifest": manifest_path.as_posix(),
        "manifest_sha256": sha256_file(manifest_path),
        "shards": len(manifest.shards),
        "total_examples": manifest.total_examples,
        "train_examples": sum(
            record.example_count for record in manifest.shards if record.split == "train"
        ),
        "development_examples": sum(
            record.example_count for record in manifest.shards if record.split == "development"
        ),
    }
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0
