# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_environment_contract.ipynb.

# %% ../notebooks/00_environment_contract.ipynb #exports-00
from __future__ import annotations

import argparse
import hashlib
import importlib.metadata as metadata
import json
import platform
import subprocess
import sys
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Final, Protocol, cast

import torch


def _find_project_root(start: Path) -> Path:
    candidate = start.resolve()
    if candidate.is_file():
        candidate = candidate.parent
    for directory in (candidate, *candidate.parents):
        if (directory / "uv.lock").is_file():
            return directory
    raise FileNotFoundError(f"could not find uv.lock from {start}")


PROJECT_ROOT: Final[Path] = _find_project_root(
    Path(__file__) if "__file__" in globals() else Path.cwd()
)


class _CudaDeviceProperties(Protocol):
    name: str
    total_memory: int


class _CudaApi(Protocol):
    def is_available(self) -> bool: ...

    def get_device_properties(self, device: int) -> _CudaDeviceProperties: ...


@dataclass(frozen=True, slots=True)
class EnvironmentReport:
    os: str
    os_release: str
    architecture: str
    python: str
    torch: str
    torch_cuda_runtime: str | None
    cuda_available: bool
    gpu_name: str | None
    gpu_memory_mib: int | None
    nvidia_driver: str | None
    uv: str | None
    nbdev: str
    ruff: str
    pyright: str
    lock_sha256: str


def _version(distribution: str) -> str:
    return metadata.version(distribution)


def _command_version(command: Sequence[str]) -> str | None:
    try:
        completed = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None
    first_line = completed.stdout.strip().splitlines()
    return first_line[0] if first_line else None


def _lock_sha256(project_root: Path) -> str:
    lock_path = project_root / "uv.lock"
    return hashlib.sha256(lock_path.read_bytes()).hexdigest()


def collect_environment_report(project_root: Path | None = None) -> EnvironmentReport:
    root = (project_root or PROJECT_ROOT).resolve()
    cuda = cast(_CudaApi, torch.cuda)
    cuda_available = cuda.is_available()
    gpu_name: str | None = None
    gpu_memory_mib: int | None = None
    if cuda_available:
        properties = cuda.get_device_properties(0)
        gpu_name = properties.name
        gpu_memory_mib = round(properties.total_memory / 1024**2)

    driver_line = _command_version(
        ["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"]
    )
    return EnvironmentReport(
        os=platform.system(),
        os_release=platform.release(),
        architecture=platform.machine(),
        python=platform.python_version(),
        torch=torch.__version__,
        torch_cuda_runtime=torch.version.cuda,
        cuda_available=cuda_available,
        gpu_name=gpu_name,
        gpu_memory_mib=gpu_memory_mib,
        nvidia_driver=driver_line,
        uv=_command_version(["uv", "--version"]),
        nbdev=_version("nbdev"),
        ruff=_version("ruff"),
        pyright=_version("pyright"),
        lock_sha256=_lock_sha256(root),
    )


def report_as_json(report: EnvironmentReport) -> str:
    return json.dumps(asdict(report), indent=2, sort_keys=True)


def validate_canonical_windows_cuda(report: EnvironmentReport) -> tuple[str, ...]:
    problems: list[str] = []
    if report.os != "Windows":
        problems.append("canonical diagnostics require native Windows")
    if not report.cuda_available:
        problems.append("the locked PyTorch build cannot access CUDA")
    if report.gpu_name != "NVIDIA GeForce RTX 4070 SUPER":
        problems.append(f"expected RTX 4070 SUPER, found {report.gpu_name!r}")
    if report.gpu_memory_mib is None or report.gpu_memory_mib < 12_000:
        problems.append("expected at least 12,000 MiB of reported GPU memory")
    return tuple(problems)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Report the locked Transformer environment")
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    parser.add_argument(
        "--require-canonical-gpu",
        action="store_true",
        help="fail unless native Windows can access the expected RTX 4070 SUPER",
    )
    args = parser.parse_args(argv)
    report = collect_environment_report()
    print(report_as_json(report) if args.json else report)
    if args.require_canonical_gpu:
        problems = validate_canonical_windows_cuda(report)
        if problems:
            print("; ".join(problems), file=sys.stderr)
            return 1
    return 0

# %% auto #0
__all__ = ['PROJECT_ROOT', 'EnvironmentReport', 'collect_environment_report', 'report_as_json', 'validate_canonical_windows_cuda',
           'main']
