"""**Status:** in progress; embeddings and sinusoidal positions are complete."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03_transformer.ipynb.

# %% auto #0
__all__ = ['TokenEmbedding', 'sinusoidal_position_table', 'SinusoidalPositionalEncoding']

# %% ../notebooks/03_transformer.ipynb #bd7e42c5a5e64a53
import torch
from torch import nn


class TokenEmbedding(nn.Module):
    """Look up token vectors and apply the paper's embedding scale.

    Each token ID selects one learned vector with `d_model` values. Following
    section 3.4 of the Transformer paper, the vector is multiplied by
    `sqrt(d_model)` before positional information is added.
    """

    def __init__(self, vocab_size: int, d_model: int) -> None:
        super().__init__()
        # One learned row per vocabulary token; each row has `d_model` values.
        self.embedding = nn.Embedding(vocab_size, d_model)
        # Paper section 3.4: strengthen token identity relative to the fixed
        # sinusoidal values that will be added to this vector.
        self.scale = d_model**0.5

    def forward(self, token_ids: torch.Tensor) -> torch.Tensor:
        """Return scaled vectors with shape (batch, sequence, d_model)."""
        # Scaling changes magnitude but preserves shape and token order.
        return self.embedding(token_ids) * self.scale

# %% ../notebooks/03_transformer.ipynb #4e7457d110ae1952
def sinusoidal_position_table(max_length: int, d_model: int) -> torch.Tensor:
    """Build the paper's fixed sine/cosine position vectors.

    The returned tensor has shape `(max_length, d_model)`. Each row represents
    one sequence position. Even columns contain sine values and their adjacent
    odd columns contain cosine values computed with the same frequency.
    """

    if d_model % 2 != 0:
        raise ValueError("d_model must be even so sine/cosine dimensions can pair")

    positions = torch.arange(max_length, dtype=torch.float32).unsqueeze(1)
    pair_indices = torch.arange(d_model // 2, dtype=torch.float32)

    # This directly represents the paper's denominator: 10000^(2i / d_model).
    denominators = 10000.0 ** ((2 * pair_indices) / d_model)
    angles = positions / denominators

    table = torch.zeros(max_length, d_model)

    # PE(pos, 2i): `:` keeps every position row; `0::2` selects even
    # dimensions 0, 2, 4, ... for sine values.
    table[:, 0::2] = torch.sin(angles)

    # PE(pos, 2i + 1): `1::2` selects the adjacent odd dimensions
    # 1, 3, 5, ... for cosine values at the same frequencies.
    table[:, 1::2] = torch.cos(angles)

    return table

# %% ../notebooks/03_transformer.ipynb #452bececf61eba17
class SinusoidalPositionalEncoding(nn.Module):
    """Add the paper's fixed sinusoidal position vectors to token vectors.

    The fixed table is stored as a buffer rather than a trainable parameter.
    During `forward`, the module selects one table row per token position and
    broadcasts those rows across every sequence in the batch.
    """

    position_table: torch.Tensor

    def __init__(self, max_length: int, d_model: int) -> None:
        super().__init__()

        table = sinusoidal_position_table(
            max_length=max_length,
            d_model=d_model,
        )

        # A buffer is saved and moved with the module but is not learned.
        self.register_buffer("position_table", table)

    def forward(self, token_vectors: torch.Tensor) -> torch.Tensor:
        """Add positions to a `(batch, sequence, d_model)` tensor."""

        sequence_length = token_vectors.shape[1]

        if sequence_length > self.position_table.shape[0]:
            raise ValueError("sequence length exceeds the position table")

        # Select one position row per token, then add a batch axis so the same
        # position pattern broadcasts across every sequence in the batch.
        positions = self.position_table[:sequence_length].unsqueeze(0)

        return token_vectors + positions
