"""**Status:** complete."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03_transformer.ipynb.

# %% auto #0
__all__ = ['TokenEmbedding', 'sinusoidal_position_table', 'SinusoidalPositionalEncoding', 'scaled_dot_product_attention',
           'MultiHeadAttention', 'PositionwiseFeedForward', 'EncoderLayer', 'Encoder', 'make_padding_mask',
           'make_causal_mask', 'DecoderLayer', 'Decoder', 'Transformer', 'greedy_decode']

# %% ../notebooks/03_transformer.ipynb #bd7e42c5a5e64a53
import torch
from torch import nn


class TokenEmbedding(nn.Module):
    """Look up token vectors and apply the paper's embedding scale.

    Each token ID selects one learned vector with `d_model` values. Following
    section 3.4 of the Transformer paper, the vector is multiplied by
    `sqrt(d_model)` before positional information is added.
    """

    def __init__(self, vocab_size: int, d_model: int) -> None:
        super().__init__()
        # One learned row per vocabulary token; each row has `d_model` values.
        self.embedding = nn.Embedding(vocab_size, d_model)
        # Paper section 3.4: strengthen token identity relative to the fixed
        # sinusoidal values that will be added to this vector.
        self.scale = d_model**0.5

    def forward(self, token_ids: torch.Tensor) -> torch.Tensor:
        """Return scaled vectors with shape (batch, sequence, d_model)."""
        # Scaling changes magnitude but preserves shape and token order.
        return self.embedding(token_ids) * self.scale

# %% ../notebooks/03_transformer.ipynb #4e7457d110ae1952
def sinusoidal_position_table(max_length: int, d_model: int) -> torch.Tensor:
    """Build the paper's fixed sine/cosine position vectors.

    The returned tensor has shape `(max_length, d_model)`. Each row represents
    one sequence position. Even columns contain sine values and their adjacent
    odd columns contain cosine values computed with the same frequency.
    """

    if d_model % 2 != 0:
        raise ValueError("d_model must be even so sine/cosine dimensions can pair")

    positions = torch.arange(max_length, dtype=torch.float32).unsqueeze(1)
    pair_indices = torch.arange(d_model // 2, dtype=torch.float32)

    # This directly represents the paper's denominator: 10000^(2i / d_model).
    denominators = 10000.0 ** ((2 * pair_indices) / d_model)
    angles = positions / denominators

    table = torch.zeros(max_length, d_model)

    # PE(pos, 2i): `:` keeps every position row; `0::2` selects even
    # dimensions 0, 2, 4, ... for sine values.
    table[:, 0::2] = torch.sin(angles)

    # PE(pos, 2i + 1): `1::2` selects the adjacent odd dimensions
    # 1, 3, 5, ... for cosine values at the same frequencies.
    table[:, 1::2] = torch.cos(angles)

    return table

# %% ../notebooks/03_transformer.ipynb #452bececf61eba17
class SinusoidalPositionalEncoding(nn.Module):
    """Add the paper's fixed sinusoidal position vectors to token vectors.

    The fixed table is stored as a buffer rather than a trainable parameter.
    During `forward`, the module selects one table row per token position and
    broadcasts those rows across every sequence in the batch.
    """

    position_table: torch.Tensor

    def __init__(self, max_length: int, d_model: int) -> None:
        super().__init__()

        table = sinusoidal_position_table(
            max_length=max_length,
            d_model=d_model,
        )

        # A buffer is saved and moved with the module but is not learned.
        self.register_buffer("position_table", table)

    def forward(self, token_vectors: torch.Tensor) -> torch.Tensor:
        """Add positions to a `(batch, sequence, d_model)` tensor."""

        sequence_length = token_vectors.shape[1]

        if sequence_length > self.position_table.shape[0]:
            raise ValueError("sequence length exceeds the position table")

        # Select one position row per token, then add a batch axis so the same
        # position pattern broadcasts across every sequence in the batch.
        positions = self.position_table[:sequence_length].unsqueeze(0)

        return token_vectors + positions

# %% ../notebooks/03_transformer.ipynb #aeb147ee6992a90f
def scaled_dot_product_attention(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    mask: torch.Tensor | None = None,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Compute explicit scaled dot-product attention.

    Args:
        query: Floating-point tensor shaped `(..., query_length, d_k)`.
        key: Floating-point tensor shaped `(..., key_len   gth, d_k)`.
        value: Floating-point tensor shaped `(..., key_length, d_v)`.
        mask: Optional Boolean tensor broadcastable to
            `(..., query_length, key_length)`. `True` entries are blocked.

    Returns:
        A pair containing:
        - contextual vectors shaped `(..., query_length, d_v)`;
        - normalized attention scores shaped
          `(..., query_length, key_length)`.
    """
    # Scalar width shared by every query and key vector.
    d_k = key.shape[-1]

    # query: (..., query_length, d_k)
    # key.transpose(-2, -1): (..., d_k, key_length)
    # attention_logits: (..., query_length, key_length)
    attention_logits = query @ key.transpose(-2, -1)

    # Scaling changes values but preserves the query-key matrix shape.
    # attention_logits: (..., query_length, key_length)
    attention_logits = attention_logits / d_k**0.5

    if mask is not None:
        # mask: broadcastable to (..., query_length, key_length)
        # attention_logits: (..., query_length, key_length)
        attention_logits = attention_logits.masked_fill(mask, -torch.inf)

    # Normalize across key positions for every query independently.
    # attention_scores: (..., query_length, key_length)
    attention_scores = torch.softmax(attention_logits, dim=-1)

    # attention_scores: (..., query_length, key_length)
    # value: (..., key_length, d_v)
    # output: (..., query_length, d_v)
    output = attention_scores @ value

    return output, attention_scores

# %% ../notebooks/03_transformer.ipynb #d7d7c2218148b89d
class MultiHeadAttention(nn.Module):
    """Paper-style multi-head self-attention and cross-attention.

    Inputs use `(batch, sequence, d_model)`. Internally, projections use
    `(batch, num_heads, sequence, d_head)`, where
    `d_head = d_model // num_heads`.
    """

    d_model: int
    num_heads: int
    d_head: int
    query_projection: nn.Linear
    key_projection: nn.Linear
    value_projection: nn.Linear
    output_projection: nn.Linear

    def __init__(self, d_model: int, num_heads: int) -> None:
        super().__init__()

        if d_model % num_heads != 0:
            raise ValueError("d_model must be divisible by num_heads")

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_head = d_model // num_heads

        self.query_projection = nn.Linear(d_model, d_model)
        self.key_projection = nn.Linear(d_model, d_model)
        self.value_projection = nn.Linear(d_model, d_model)
        self.output_projection = nn.Linear(d_model, d_model)

    def forward(
        self,
        query: torch.Tensor,
        key: torch.Tensor,
        value: torch.Tensor,
        mask: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Run attention over batched model vectors.

        Args:
            query: `(batch, query_length, d_model)`.
            key: `(batch, key_length, d_model)`.
            value: `(batch, key_length, d_model)`.
            mask: Boolean tensor broadcastable to
                `(batch, num_heads, query_length, key_length)`.

        Returns:
            Output vectors shaped `(batch, query_length, d_model)` and
                attention_scores shaped
               `(batch, num_heads, query_length, key_length)`.
        """
        # Read the dimensions needed to reshape the projected tensors.
        # query: (batch, query_length, d_model)
        # key/value: (batch, key_length, d_model)
        batch_size = query.shape[0]
        query_length = query.shape[1]
        key_length = key.shape[1]

        # Learn separate query, key, and value representations. Each linear
        # projection preserves its input shape and total width `d_model`.
        # projected_queries: (batch, query_length, d_model)
        # projected_keys/values: (batch, key_length, d_model)
        projected_queries = self.query_projection(query)
        projected_keys = self.key_projection(key)
        projected_values = self.value_projection(value)

        # Split `d_model` into `num_heads * d_head`, then move the head axis
        # before the sequence axis so every head attends independently.
        # queries: (batch, num_heads, query_length, d_head)
        queries = projected_queries.reshape(
            batch_size,
            query_length,
            self.num_heads,
            self.d_head,
        ).transpose(1, 2)

        # keys: (batch, num_heads, key_length, d_head)
        keys = projected_keys.reshape(
            batch_size,
            key_length,
            self.num_heads,
            self.d_head,
        ).transpose(1, 2)

        # values: (batch, num_heads, key_length, d_head)
        values = projected_values.reshape(
            batch_size,
            key_length,
            self.num_heads,
            self.d_head,
        ).transpose(1, 2)

        # Every head compares each query with every key and retrieves a
        # weighted mixture of that head's value vectors.
        # attended_values: (batch, num_heads, query_length, d_head)
        # attention_scores: (batch, num_heads, query_length, key_length)
        attended_values, attention_scores = scaled_dot_product_attention(
            query=queries,
            key=keys,
            value=values,
            mask=mask,
        )

        # Move heads beside one another and concatenate their `d_head` values
        # back into one `d_model` vector for each query position.
        # joined_heads: (batch, query_length, d_model)
        joined_heads = attended_values.transpose(1, 2).reshape(
            batch_size,
            query_length,
            self.d_model,
        )

        # Let the model learn how to combine information from all heads.
        # output: (batch, query_length, d_model)
        output = self.output_projection(joined_heads)

        return output, attention_scores

# %% ../notebooks/03_transformer.ipynb #9eec06ad4e244197
class PositionwiseFeedForward(nn.Module):
    """Apply the paper's two-layer ReLU network at every token position."""

    d_model: int
    d_ff: int
    input_projection: nn.Linear
    output_projection: nn.Linear

    def __init__(self, d_model: int, d_ff: int) -> None:
        super().__init__()

        self.d_model = d_model
        self.d_ff = d_ff

        self.input_projection = nn.Linear(d_model, d_ff)
        self.output_projection = nn.Linear(d_ff, d_model)

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        """Transform `(batch, sequence, d_model)` token vectors."""
        # Expand each token independently.
        # expanded: (batch, sequence, d_ff)
        expanded = self.input_projection(inputs)

        # Keep positive activations and replace negative values with zero.
        # activated: (batch, sequence, d_ff)
        activated = torch.relu(expanded)

        # Return each token to the model width.
        # output: (batch, sequence, d_model)
        output = self.output_projection(activated)

        return output

# %% ../notebooks/03_transformer.ipynb #7c7bfcb5fa4f028b
class EncoderLayer(nn.Module):
    """One paper-faithful post-norm Transformer encoder layer."""

    self_attention: MultiHeadAttention
    feed_forward: PositionwiseFeedForward
    attention_dropout: nn.Dropout
    attention_norm: nn.LayerNorm
    feed_forward_dropout: nn.Dropout
    feed_forward_norm: nn.LayerNorm

    def __init__(
        self,
        d_model: int,
        num_heads: int,
        d_ff: int,
        dropout: float = 0.1,
    ) -> None:
        super().__init__()

        self.self_attention = MultiHeadAttention(
            d_model=d_model,
            num_heads=num_heads,
        )
        self.feed_forward = PositionwiseFeedForward(
            d_model=d_model,
            d_ff=d_ff,
        )

        self.attention_dropout = nn.Dropout(dropout)
        self.attention_norm = nn.LayerNorm(d_model)

        self.feed_forward_dropout = nn.Dropout(dropout)
        self.feed_forward_norm = nn.LayerNorm(d_model)

    def forward(
        self,
        inputs: torch.Tensor,
        source_mask: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Encode `(batch, source_length, d_model)` vectors."""
        # Self-attention lets every source token gather information from the
        # source sequence.
        # attention_output: (batch, source_length, d_model)
        # attention_scores:
        #   (batch, num_heads, source_length, source_length)
        attention_output, _ = self.self_attention(
            query=inputs,
            key=inputs,
            value=inputs,
            mask=source_mask,
        )

        # Paper-faithful post-norm:
        # LayerNorm(inputs + Dropout(attention_output))
        # after_attention: (batch, source_length, d_model)
        after_attention = self.attention_norm(inputs + self.attention_dropout(attention_output))

        # Transform each contextualized source token independently.
        # feed_forward_output: (batch, source_length, d_model)
        feed_forward_output = self.feed_forward(after_attention)

        # Second paper-faithful post-norm residual path.
        # output: (batch, source_length, d_model)
        output = self.feed_forward_norm(
            after_attention + self.feed_forward_dropout(feed_forward_output)
        )

        return output

# %% ../notebooks/03_transformer.ipynb #199088857242e4f8
class Encoder(nn.Module):
    """Apply a stack of independent Transformer encoder layers."""

    layers: nn.ModuleList

    def __init__(
        self,
        d_model: int,
        num_heads: int,
        d_ff: int,
        dropout: float = 0.1,
        num_layers: int = 6,
    ) -> None:
        super().__init__()

        # Construct a new EncoderLayer on every iteration. Do not repeat one
        # existing layer object, because all layers must own separate weights.
        self.layers = nn.ModuleList(
            [
                EncoderLayer(
                    d_model=d_model,
                    num_heads=num_heads,
                    d_ff=d_ff,
                    dropout=dropout,
                )
                for _ in range(num_layers)
            ]
        )

    def forward(
        self, inputs: torch.Tensor, source_mask: torch.Tensor | None = None
    ) -> torch.Tensor:
        """Encode `(batch, source_length, d_model)` source vectors."""
        # output: (batch, source_length, d_model)
        output = inputs

        # Every iteration preserves the tensor shape while applying a new set
        # of self-attention, FFN, and normalization parameters.
        for layer in self.layers:
            output = layer(
                inputs=output,
                source_mask=source_mask,
            )

        # output: (batch, source_length, d_model)
        return output

# %% ../notebooks/03_transformer.ipynb #51441a5fae69220d
def make_padding_mask(
    token_ids: torch.Tensor,
    pad_token_id: int,
) -> torch.Tensor:
    """Block padding keys in `(batch, sequence_length)` token IDs."""
    # token_ids == pad_token_id: (batch, sequence_length)
    padding_positions = token_ids.eq(pad_token_id)

    # Add head and query axes so this broadcasts against attention scores.
    # mask: (batch, 1, 1, sequence_length)
    mask = padding_positions[:, None, None, :]

    return mask


#| export
def make_causal_mask(
    sequence_length: int,
    device: torch.device | None = None,
) -> torch.Tensor:
    """Block future target keys for every target query."""
    # Start with one Boolean decision for every query-key pair.
    # future_positions: (sequence_length, sequence_length)
    future_positions = torch.triu(
        torch.ones(
            sequence_length,
            sequence_length,
            dtype=torch.bool,
            device=device,
        ),
        diagonal=1,
    )

    # Reuse this rule across all batches and attention heads.
    # mask: (1, 1, sequence_length, sequence_length)
    mask = future_positions[None, None, :, :]

    return mask

# %% ../notebooks/03_transformer.ipynb #fa1ce7d18d05344b
class DecoderLayer(nn.Module):
    """One paper-faithful post-norm Transformer decoder layer."""

    masked_multihead_attention: MultiHeadAttention
    masked_multihead_attention_dropout: nn.Dropout
    masked_multihead_attention_norm: nn.LayerNorm
    cross_attention: MultiHeadAttention
    cross_attention_dropout: nn.Dropout
    cross_attention_norm: nn.LayerNorm
    feed_forward: PositionwiseFeedForward
    feed_forward_dropout: nn.Dropout
    feed_forward_norm: nn.LayerNorm

    def __init__(
        self,
        d_model: int,
        num_heads: int,
        d_ff: int,
        dropout: float = 0.1,
    ) -> None:
        super().__init__()

        self.masked_multihead_attention = MultiHeadAttention(
            d_model=d_model,
            num_heads=num_heads,
        )
        self.masked_multihead_attention_dropout = nn.Dropout(dropout)
        self.masked_multihead_attention_norm = nn.LayerNorm(d_model)

        self.cross_attention = MultiHeadAttention(
            d_model=d_model,
            num_heads=num_heads,
        )
        self.cross_attention_dropout = nn.Dropout(dropout)
        self.cross_attention_norm = nn.LayerNorm(d_model)

        self.feed_forward = PositionwiseFeedForward(
            d_model=d_model,
            d_ff=d_ff,
        )
        self.feed_forward_dropout = nn.Dropout(dropout)
        self.feed_forward_norm = nn.LayerNorm(d_model)

    def forward(
        self,
        inputs: torch.Tensor,
        memory: torch.Tensor,
        target_mask: torch.Tensor | None = None,
        source_mask: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Decode target vectors using encoded source memory.

        Args:
            inputs: Target vectors shaped `(batch, target_length, d_model)`.
            memory: Encoder output shaped `(batch, source_length, d_model)`.
            target_mask: Boolean mask broadcastable to target self-attention scores.
            source_mask: Boolean mask broadcastable to cross-attention scores.

        Returns:
            Target vectors shaped `(batch, target_length, d_model)`.
        """
        # Masked self-attention lets each target token gather information only
        # from target positions permitted by the padding and causal mask.
        # masked_multihead_attention_output: (batch, target_length, d_model)
        masked_multihead_attention_output, _ = self.masked_multihead_attention(
            query=inputs,
            key=inputs,
            value=inputs,
            mask=target_mask,
        )

        # Preserve the original target state through the first residual path,
        # then apply paper-faithful post-norm.
        # after_multihead_attention: (batch, target_length, d_model)
        after_multihead_attention = self.masked_multihead_attention_norm(
            inputs + self.masked_multihead_attention_dropout(masked_multihead_attention_output)
        )

        # Cross-attention uses decoder states as queries and encoder memory as
        # keys and values, letting each target position read the source.
        # cross_attention_output: (batch, target_length, d_model)
        cross_attention_output, _ = self.cross_attention(
            query=after_multihead_attention,
            key=memory,
            value=memory,
            mask=source_mask,
        )

        # Preserve the post-self-attention decoder state through the second
        # residual path, then apply post-norm.
        # after_cross_attention: (batch, target_length, d_model)
        after_cross_attention = self.cross_attention_norm(
            after_multihead_attention + self.cross_attention_dropout(cross_attention_output)
        )

        # Transform each source-aware target position independently without
        # mixing sequence positions.
        # feed_forward_output: (batch, target_length, d_model)
        feed_forward_output = self.feed_forward(after_cross_attention)

        # Preserve the source-aware decoder state through the third residual
        # path, then apply the final post-norm.
        # output: (batch, target_length, d_model)
        output = self.feed_forward_norm(
            after_cross_attention + self.feed_forward_dropout(feed_forward_output)
        )

        return output

# %% ../notebooks/03_transformer.ipynb #ad4350e8b51443d9
class Decoder(nn.Module):
    """Apply a stack of independent Transformer decoder layers."""

    layers: nn.ModuleList

    def __init__(
        self,
        d_model: int,
        num_heads: int,
        d_ff: int,
        dropout: float = 0.1,
        num_layers: int = 6,
    ) -> None:
        super().__init__()

        # Construct a new DecoderLayer on every iteration. Do not repeat one
        # existing layer object, because all layers must own separate weights.
        self.layers = nn.ModuleList(
            [
                DecoderLayer(
                    d_model=d_model,
                    num_heads=num_heads,
                    d_ff=d_ff,
                    dropout=dropout,
                )
                for _ in range(num_layers)
            ]
        )

    def forward(
        self,
        inputs: torch.Tensor,
        memory: torch.Tensor,
        source_mask: torch.Tensor | None = None,
        target_mask: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Decode `(batch, target_length, d_model)` target vectors."""
        # output: (batch, target_length, d_model)
        output = inputs

        # Every iteration preserves the tensor shape while applying a new set
        # of masked-multihead-attention, cross-attention, FFN, and normalization parameters.
        for layer in self.layers:
            output = layer(
                inputs=output,
                memory=memory,
                source_mask=source_mask,
                target_mask=target_mask,
            )

        # output: (batch, target_length, d_model)
        return output

# %% ../notebooks/03_transformer.ipynb #5185f79b3cfe345c
class Transformer(nn.Module):
    """Complete paper-style encoder-decoder Transformer."""

    pad_token_id: int

    token_embedding: TokenEmbedding
    positional_encoding: SinusoidalPositionalEncoding
    embedding_dropout: nn.Dropout
    encoder: Encoder
    decoder: Decoder
    output_projection: nn.Linear

    def __init__(
        self,
        vocab_size: int,
        d_model: int,
        num_heads: int,
        d_ff: int,
        max_length: int,
        pad_token_id: int,
        dropout: float = 0.1,
        num_layers: int = 6,
    ) -> None:
        super().__init__()

        self.pad_token_id = pad_token_id

        # One embedding table is shared by source and target token IDs.
        self.token_embedding = TokenEmbedding(
            vocab_size=vocab_size,
            d_model=d_model,
        )
        self.positional_encoding = SinusoidalPositionalEncoding(
            max_length=max_length,
            d_model=d_model,
        )
        self.embedding_dropout = nn.Dropout(dropout)

        self.encoder = Encoder(
            d_model=d_model,
            num_heads=num_heads,
            d_ff=d_ff,
            dropout=dropout,
            num_layers=num_layers,
        )
        self.decoder = Decoder(
            d_model=d_model,
            num_heads=num_heads,
            d_ff=d_ff,
            dropout=dropout,
            num_layers=num_layers,
        )

        # Produce one score per vocabulary token without a separate bias.
        self.output_projection = nn.Linear(
            d_model,
            vocab_size,
            bias=False,
        )

        # Paper-faithful weight tying: output logits reuse the same learned
        # matrix that converts source and target token IDs into vectors.
        self.output_projection.weight = self.token_embedding.embedding.weight

    def forward(
        self,
        source_token_ids: torch.Tensor,
        target_token_ids: torch.Tensor,
    ) -> torch.Tensor:
        """Return next-token vocabulary logits.

        Args:
            source_token_ids: Integer IDs shaped `(batch, source_length)`.
            target_token_ids: Integer target-prefix IDs shaped
                `(batch, target_length)`.

        Returns:
            Floating-point logits shaped
            `(batch, target_length, vocab_size)`.
        """
        # source_token_ids: (batch, source_length)
        # source_mask: (batch, 1, 1, source_length)
        source_mask = make_padding_mask(
            token_ids=source_token_ids,
            pad_token_id=self.pad_token_id,
        )

        # target_padding_mask: (batch, 1, 1, target_length)
        target_padding_mask = make_padding_mask(
            token_ids=target_token_ids,
            pad_token_id=self.pad_token_id,
        )

        # causal_mask: (1, 1, target_length, target_length)
        causal_mask = make_causal_mask(
            sequence_length=target_token_ids.shape[1],
            device=target_token_ids.device,
        )

        # Broadcasting combines both target visibility rules.
        # target_mask: (batch, 1, target_length, target_length)
        target_mask = target_padding_mask | causal_mask

        # TokenEmbedding scales vectors by sqrt(d_model), positional encoding
        # adds order information, and dropout regularizes their sum.
        # source_vectors: (batch, source_length, d_model)
        source_vectors = self.embedding_dropout(
            self.positional_encoding(self.token_embedding(source_token_ids))
        )

        # target_vectors: (batch, target_length, d_model)
        target_vectors = self.embedding_dropout(
            self.positional_encoding(self.token_embedding(target_token_ids))
        )

        # Encode the complete source sequence.
        # memory: (batch, source_length, d_model)
        memory = self.encoder(
            inputs=source_vectors,
            source_mask=source_mask,
        )

        # Decode each target prefix position against encoder memory.
        # decoder_states: (batch, target_length, d_model)
        decoder_states = self.decoder(
            inputs=target_vectors,
            memory=memory,
            source_mask=source_mask,
            target_mask=target_mask,
        )

        # Convert every decoder state into vocabulary scores.
        # logits: (batch, target_length, vocab_size)
        logits = self.output_projection(decoder_states)

        return logits

# %% ../notebooks/03_transformer.ipynb #32a94864f4188ad6
@torch.no_grad()
def greedy_decode(
    model: Transformer,
    source_token_ids: torch.Tensor,
    bos_token_id: int,
    max_new_tokens: int,
) -> torch.Tensor:
    """Generate fixed-length target IDs using greedy next-token choices."""
    batch_size = source_token_ids.shape[0]

    # generated: (batch, current_target_length=1)
    generated = torch.full(
        (batch_size, 1),
        bos_token_id,
        dtype=torch.long,
        device=source_token_ids.device,
    )

    for _ in range(max_new_tokens):
        # logits: (batch, current_target_length, vocab_size)
        logits = model(
            source_token_ids=source_token_ids,
            target_token_ids=generated,
        )

        # Only the final decoder position predicts the next token.
        # next_token_ids: (batch, 1)
        next_token_ids = logits[:, -1].argmax(
            dim=-1,
            keepdim=True,
        )

        # generated: (batch, current_target_length + 1)
        generated = torch.cat(
            [generated, next_token_ids],
            dim=1,
        )

    return generated
