"""**Status:** implementation in progress."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/04_objective_optimizer_batching.ipynb.

# %% auto #0
__all__ = ['label_smoothed_loss', 'noam_learning_rate', 'padded_token_counts', 'make_token_budget_batches']

# %% ../notebooks/04_objective_optimizer_batching.ipynb #9fc597b44619869
import torch
import torch.nn.functional as F


def label_smoothed_loss(
    logits: torch.Tensor,
    targets: torch.Tensor,
    pad_token_id: int,
    smoothing: float = 0.1,
) -> torch.Tensor:
    """Return mean label-smoothed loss over non-padding target positions.

    `logits` has shape `(batch, target_length, vocabulary_size)`, and
    `targets` has shape `(batch, target_length)`.
    """
    # Cross-entropy expects class scores shaped (batch, vocabulary, sequence),
    # so move the vocabulary axis before the target-length axis.
    return F.cross_entropy(
        logits.transpose(1, 2),
        targets,
        # Padding fills batch storage but does not represent a prediction target.
        ignore_index=pad_token_id,
        # Use the paper's regularization strength instead of a hard one-hot target.
        label_smoothing=smoothing,
    )

# %% ../notebooks/04_objective_optimizer_batching.ipynb #d004cdc9ca9fbd64
def noam_learning_rate(
    step: int,
    d_model: int,
    warmup_steps: int = 4_000,
) -> float:
    """Return the paper's learning rate for one optimizer step."""
    model_scale = d_model**-0.5
    decay = step**-0.5
    warmup = step * warmup_steps**-1.5

    return model_scale * min(decay, warmup)

# %% ../notebooks/04_objective_optimizer_batching.ipynb #28ceb5690d844c7c
from collections.abc import Sequence


def padded_token_counts(
    batch: Sequence[tuple[Sequence[int], Sequence[int]]],
) -> tuple[int, int]:
    """Return padded source and target token positions for one batch."""
    if not batch:
        return 0, 0

    batch_size = len(batch)
    maximum_source_length = max(len(source_ids) for source_ids, _ in batch)
    maximum_target_length = max(len(target_ids) for _, target_ids in batch)

    return (
        batch_size * maximum_source_length,
        batch_size * maximum_target_length,
    )

# %% ../notebooks/04_objective_optimizer_batching.ipynb #token-budget-batcher-code-04
def make_token_budget_batches(
    examples: Sequence[tuple[Sequence[int], Sequence[int]]],
    token_budget: int,
) -> list[list[tuple[Sequence[int], Sequence[int]]]]:
    """Group ordered token pairs within a padded-token budget per side."""
    if token_budget < 1:
        raise ValueError("token_budget must be positive")

    batches: list[list[tuple[Sequence[int], Sequence[int]]]] = []
    current_batch: list[tuple[Sequence[int], Sequence[int]]] = []

    for example in examples:
        source_ids, target_ids = example
        if len(source_ids) > token_budget or len(target_ids) > token_budget:
            raise ValueError("one example exceeds the token budget")

        candidate_batch = [*current_batch, example]
        source_positions, target_positions = padded_token_counts(candidate_batch)
        candidate_exceeds_budget = (
            source_positions > token_budget or target_positions > token_budget
        )

        if current_batch and candidate_exceeds_budget:
            batches.append(current_batch)
            current_batch = [example]
        else:
            current_batch = candidate_batch

    if current_batch:
        batches.append(current_batch)

    return batches
