# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/05_training_validation_cli.ipynb.

# %% auto #0
__all__ = ['train', 'validate']

# %% ../notebooks/05_training_validation_cli.ipynb #845198fc63f0443d
from collections.abc import Sequence

import torch

from .model import Transformer
from .optimization import label_smoothed_loss

# %% ../notebooks/05_training_validation_cli.ipynb #781ead6e079b2f7
def train(
    model: Transformer,
    batches: Sequence[tuple[torch.Tensor, torch.Tensor]],
    optimizer: torch.optim.Optimizer,
) -> float:
    """Run one parameter-updating pass and return its mean batch loss."""
    if len(batches) == 0:
        raise ValueError("Cannot compute loss on empty sequence of batches.")

    total_loss = 0.0
    model.train()
    for source_token_ids, target_token_ids in batches:
        optimizer.zero_grad()

        decoder_input_ids = target_token_ids[:, :-1]
        logits = model(
            source_token_ids=source_token_ids,
            target_token_ids=decoder_input_ids,
        )

        next_token_labels = target_token_ids[:, 1:]
        loss = label_smoothed_loss(
            logits=logits,
            targets=next_token_labels,
            pad_token_id=model.pad_token_id,
        )
        loss.backward()

        optimizer.step()
        total_loss += loss.item()

    return total_loss / len(batches)

# %% ../notebooks/05_training_validation_cli.ipynb #2f26241bc83c0568
@torch.no_grad()
def validate(
    model: Transformer,
    batches: Sequence[tuple[torch.Tensor, torch.Tensor]],
) -> float:
    """Return mean batch loss in evaluation mode without gradients."""
    if len(batches) == 0:
        raise ValueError("Cannot compute loss on empty sequence of batches.")

    total_loss = 0.0
    model.eval()
    for source_token_ids, target_token_ids in batches:
        decoder_input_ids = target_token_ids[:, :-1]
        logits = model(
            source_token_ids=source_token_ids,
            target_token_ids=decoder_input_ids,
        )

        next_token_labels = target_token_ids[:, 1:]
        loss = label_smoothed_loss(
            logits=logits,
            targets=next_token_labels,
            pad_token_id=model.pad_token_id,
        )
        total_loss += loss.item()

    return total_loss / len(batches)
