# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/05_training_validation_cli.ipynb.

# %% auto #0
__all__ = ['train', 'validate', 'main']

# %% ../notebooks/05_training_validation_cli.ipynb #845198fc63f0443d
import argparse
import json
from collections.abc import Sequence
from typing import cast

import torch

from .model import Transformer
from .optimization import label_smoothed_loss

# %% ../notebooks/05_training_validation_cli.ipynb #781ead6e079b2f7
def train(
    model: Transformer,
    batches: Sequence[tuple[torch.Tensor, torch.Tensor]],
    optimizer: torch.optim.Optimizer,
) -> float:
    """Run one parameter-updating pass and return its mean batch loss."""
    if len(batches) == 0:
        raise ValueError("Cannot compute loss on empty sequence of batches.")

    total_loss = 0.0
    model.train()
    for source_token_ids, target_token_ids in batches:
        optimizer.zero_grad()

        decoder_input_ids = target_token_ids[:, :-1]
        logits = model(
            source_token_ids=source_token_ids,
            target_token_ids=decoder_input_ids,
        )

        next_token_labels = target_token_ids[:, 1:]
        loss = label_smoothed_loss(
            logits=logits,
            targets=next_token_labels,
            pad_token_id=model.pad_token_id,
        )
        loss.backward()

        optimizer.step()
        total_loss += loss.item()

    return total_loss / len(batches)

# %% ../notebooks/05_training_validation_cli.ipynb #2f26241bc83c0568
@torch.no_grad()
def validate(
    model: Transformer,
    batches: Sequence[tuple[torch.Tensor, torch.Tensor]],
) -> float:
    """Return mean batch loss in evaluation mode without gradients."""
    if len(batches) == 0:
        raise ValueError("Cannot compute loss on empty sequence of batches.")

    total_loss = 0.0
    model.eval()
    for source_token_ids, target_token_ids in batches:
        decoder_input_ids = target_token_ids[:, :-1]
        logits = model(
            source_token_ids=source_token_ids,
            target_token_ids=decoder_input_ids,
        )

        next_token_labels = target_token_ids[:, 1:]
        loss = label_smoothed_loss(
            logits=logits,
            targets=next_token_labels,
            pad_token_id=model.pad_token_id,
        )
        total_loss += loss.item()

    return total_loss / len(batches)

# %% ../notebooks/05_training_validation_cli.ipynb #standalone-command-code-05
def _fixture_training_curve(
    number_of_passes: int,
) -> tuple[list[float], list[float]]:
    """Return deterministic training and validation losses for the CLI fixture."""
    if number_of_passes < 1:
        raise ValueError("number_of_passes must be positive")

    torch.manual_seed(1)
    fixture_model = Transformer(
        vocab_size=32,
        d_model=8,
        num_heads=2,
        d_ff=16,
        max_length=8,
        pad_token_id=0,
        dropout=0.0,
        num_layers=6,
    )
    fixture_optimizer = torch.optim.Adam(
        fixture_model.parameters(),
        lr=1e-3,
        betas=(0.9, 0.98),
        eps=1e-9,
    )
    fixture_batches = [
        (
            torch.tensor([[2, 5, 6, 3]], dtype=torch.long),
            torch.tensor([[2, 7, 8, 3]], dtype=torch.long),
        )
    ]

    training_losses: list[float] = []
    validation_losses: list[float] = []
    for _ in range(number_of_passes):
        training_losses.append(
            train(fixture_model, fixture_batches, fixture_optimizer)
        )
        validation_losses.append(validate(fixture_model, fixture_batches))

    return training_losses, validation_losses


def main(argv: Sequence[str] | None = None) -> int:
    """Run deterministic fixture training in a fresh process."""
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("--passes", type=int, default=20)
    args = parser.parse_args(argv)
    number_of_passes = cast(int, args.passes)
    training_losses, validation_losses = _fixture_training_curve(
        number_of_passes
    )
    print(
        json.dumps(
            {
                "training_losses": training_losses,
                "validation_losses": validation_losses,
            }
        )
    )
    return 0

